version: '3.3'

services:
  php:
    build: ./php
    container_name: api_icd10
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    networks:
      - app

networks:
  app:
    external: true